### ISSUE TITLE
How to you use next/link with antd buttons?

### ISSUE THREAD

**Issue by zomars** [hanpama/next-with-antd#4]

**Comment by hanpama** [comment]
How about this?

```jsx
<Link href='/about'>
  <Button href='/about'>
    Go About Page
  </Button>
</Link>
```
AFAIK when it renders, <Link> clones its child and give href and onClick prop if the child is an <a> element. Otherwise only onClick prop will be given to the child.

It actually works without <Button>'s href prop becuase of the onClick action, but it doesn't seem good in terms of the markup.

**Comment by zomars** [comment]
It works! Thank you for the response!
